### PR TITLE
Line and column tracking

### PR DESCRIPTION
**Pull request by nbish11**

### CODE REVIEW

**Comment by halaxa** [comment]
Great job, thanks. I noticed that the `position` property is obviously buggy from the beginning. What if you removed the pieces, where you test it? I'd rather fix it and make correct tests in another PR than make tests that test -- and thus knowingly fixate wrong behavior in place. What do you think?

**Comment by halaxa** [comment]
Also, adding some failing test with `\r\n` as line separator ;) Would you take a look at it or should I fix it?

**Comment by nbish11** [comment]
I can get this done on Thursday sometime for you.

**Comment by halaxa** [comment]
Nice, thanks. No need to rush :)

**Comment by nbish11** [comment]
@halaxa Done and done. Sorry about the force-pushs, they were just quick bug fixes.

**Comment by halaxa** [comment]
Nicely done. Thank you. See you next time :)

**Pull request merged**
