### PR TITLE
add a stand alone PSR-4 spec loader

### PR DESCRIPTION
**Pull request by a-sync**

### CODE REVIEW

**Comment by halaxa** [comment]
Thanks. The build is failing at code style check. Can you run `make cs-fix` or `composer cs-fix` to fix that, please?

Also I would like to have this covered with tests. A test can prepend this autoloader, test it and then remove it. To make it testable - autoloader file would return autoload callable and usage in the user land would then be:

```php
spl_autoload_register(require '/path/to/autoload.php');
```

**Comment by a-sync** [comment]
Sorry, but my only intent was to contribute a snippet to solve a specific problem. I only opened the PR as a curtesy, but i'm not planning to work on this.

**Comment by halaxa** [comment]
Ok, thank you for your contribution anyway ;)

**Comment by halaxa** [comment]
Will you please keep this PR here so I can finish it?

**Comment by devfrey** [comment]
These changes generate a warning when running `composer install` (I'm using Composer 2.2.7):

```
Class JsonMachine\Autoloading located in ./vendor/halaxa/json-machine/src/autoloader.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by halaxa** [comment]
Thanks, @devfrey. 7adbfef should fix this on master. Can you please verify it by requiring `dev-master`? Works for me.

**Comment by devfrey** [comment]
Works perfectly @halaxa, thanks!

**Comment by halaxa** [comment]
Released in `1.1.1`

**Pull request merged**
