### PR TITLE
Use a 'token' object-stream between the lexer and parser.

### PR DESCRIPTION
**Pull request by nbish11**
I think this will add a lot of benefits, especially in future PRs/commits (I have a few other ideas). Also by adding a 'token' object it starts to reduce complexity in the `Lexer`/`Parser` classes, as seen by the commits (the code is easier to follow along with).

The tokens produced by the lexer also now track the any linebreaks (you will see why in my next PR).

:-)

### CODE REVIEW

**Comment by halaxa** [comment]
Thank you. I understand your motivation, however I am afraid this will have an impact on performance. Can you please run performace test `tests/testPerformance.php` multiple times with and without the PR and check? Thanks.

**Comment by nbish11** [comment]
Okay I will take a look when I get a chance and let you know.

**Comment by halaxa** [comment]
Thanks. Before you invest into the next PR, can you please elaborate on why are line breaks important to you?

**Comment by nbish11** [comment]
The line breaks are only used to track the _line position_ of a token. There is no actual token defined for them. By tracking the line position, this allows the lexer to report errors from JSON streams/files that have been also been formatted and give exact positional information for lexemes (handy for syntax highlighting).

For example, if there is a 500 line JSON file (that's been formatted) and there is an error like this at line 398:

```php
    "name": "nbish11",, 
```

Then throwing an error would provide better locational information:

'Unexpected comma on line 398 at column 22.'

As it stands, the lexer only gives you the character's position within the entire JSON source. This makes tracking down errors in formatted JSON extremely time consuming.

Exception/error handling is actually the basis of my next PR.

**Comment by nbish11** [comment]
P. S. I also went to run the performance tests and discovered a bug. I'm not sure where it's coming from at the moment, but on my next day off from work, I will resolve it and give you the performance results.

**Comment by halaxa** [comment]
I know that current error reporting kind of sucks, and the idea of line numbers is on the table for some time. I like it. What about implementig it without objects, but as properties `line` and `column` on Lexer object? Currently no function call is present in performance critical/loop code. This solution with Token object brings many of them for each token processing. I'd like to keep it the old way and search for a win win solution without function calls. What do you think?

Also I have an optimization in mind to speed things up and the concept of token objects goes against it. The idea is to simply concat tokens when the parser is at iterator level and let `json_decode` do syntax checking without running slow php syntax check which is currently redundant and slows things down. Most of the Token objects would be useless then. They would be created only to get the value from them.

**Comment by nbish11** [comment]
If you want, I can close this PR, and open another one with line and column tracking instead (using methods on the lexer).

**Comment by nbish11** [comment]
See my new [PR](https://github.com/halaxa/json-machine/pull/12).

**Pull request closed without merging**
